# Generated by Django 4.2.27 on 2026-01-20 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Database Backup"),
                            ("incremental", "Incremental Backup"),
                            ("manual", "Manual Backup"),
                            ("scheduled", "Scheduled Backup"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "checksum",
                    models.CharField(
                        blank=True, help_text="SHA-256 checksum", max_length=128
                    ),
                ),
                (
                    "tables_included",
                    models.JSONField(
                        default=list, help_text="List of tables included in backup"
                    ),
                ),
                (
                    "record_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total records backed up"
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_backups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BackupSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hour",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Hour (0-23) for daily/weekly/monthly backups",
                        null=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Day of week (0=Monday, 6=Sunday) for weekly backups",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Day of month (1-31) for monthly backups",
                        null=True,
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[
                            ("full", "Full Database Backup"),
                            ("incremental", "Incremental Backup"),
                            ("manual", "Manual Backup"),
                            ("scheduled", "Scheduled Backup"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Number of days to keep backups"
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BackupRestore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "tables_to_restore",
                    models.JSONField(
                        default=list,
                        help_text="Specific tables to restore, empty means all",
                    ),
                ),
                (
                    "dry_run",
                    models.BooleanField(
                        default=False, help_text="Test run without making changes"
                    ),
                ),
                ("records_restored", models.PositiveIntegerField(default=0)),
                ("tables_restored", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("can_rollback", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "backup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restores",
                        to="backup.backup",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backup_restores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rollback_backup",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollback_for",
                        to="backup.backup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="backup",
            index=models.Index(fields=["status"], name="backup_back_status_65f323_idx"),
        ),
        migrations.AddIndex(
            model_name="backup",
            index=models.Index(
                fields=["backup_type"], name="backup_back_backup__a21851_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="backup",
            index=models.Index(
                fields=["created_at"], name="backup_back_created_e2763d_idx"
            ),
        ),
    ]
