# Generated by Django 4.2.27 on 2026-01-20 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("display_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("lease", "Lease Agreement"),
                            ("notice", "Notice/Letter"),
                            ("report", "Report"),
                            ("contract", "Contract"),
                            ("form", "Form"),
                        ],
                        max_length=50,
                    ),
                ),
                ("category", models.CharField(default="general", max_length=100)),
                (
                    "content",
                    models.TextField(
                        help_text="Template content with {{variable}} placeholders"
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=list, help_text="List of variables used in template"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_system_template", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "variables_data",
                    models.JSONField(help_text="Variable values used for generation"),
                ),
                ("generated_content", models.TextField(blank=True)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("sent", "Sent"),
                            ("signed", "Signed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("recipient_emails", models.JSONField(blank=True, default=list)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("related_model", models.CharField(blank=True, max_length=100)),
                ("related_id", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_documents",
                        to="templates.documenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
