# Generated by Django 4.2.27 on 2026-01-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generateddocument",
            name="related_model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
