# Generated by Django 6.0.1 on 2026-01-20 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('leases', '0002_initial'),
        ('maintenance', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='property_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_periods', to='properties.property'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='leases.lease'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='maintenance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='maintenance.maintenancerequest'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='property_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='properties.property'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together={('property_obj', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['property_obj'], name='accounting__propert_81c1a9_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_type'], name='accounting__transac_4eaaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['category'], name='accounting__categor_da8044_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_date'], name='accounting__transac_79b32d_idx'),
        ),
    ]
