# Generated by Django 4.2.27 on 2026-01-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["transaction_type", "transaction_date"],
                name="accounting__transac_a02795_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["property_obj", "transaction_date"],
                name="accounting__propert_2dd5b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(fields=["lease"], name="accounting__lease_i_900064_idx"),
        ),
    ]
