# Generated by Django 6.0.1 on 2026-01-20 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['lease_obj'], name='payments_re_lease_o_473b97_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['status'], name='payments_re_status_67e4ec_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['payment_date'], name='payments_re_payment_af3927_idx'),
        ),
        migrations.AddIndex(
            model_name='rentpayment',
            index=models.Index(fields=['due_date'], name='payments_re_due_dat_347e95_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rentpayment',
            unique_together={('lease_obj', 'payment_date')},
        ),
    ]
