# Generated by Django 4.2.27 on 2026-01-20 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "properties",
            "0003_property_version_alter_property_annual_property_tax_and_more",
        ),
        ("maintenance", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0001_initial"),
        ("leases", "0003_lease_version_alter_lease_deposit_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProcessingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processing_type",
                    models.CharField(
                        choices=[
                            ("lease_analysis", "Lease Document Analysis"),
                            ("tenant_application", "Tenant Application Analysis"),
                            ("maintenance_request", "Maintenance Request Analysis"),
                            ("property_inspection", "Property Inspection Analysis"),
                            ("communication", "Generated Communication"),
                            ("financial_analysis", "Financial Report Analysis"),
                        ],
                        help_text="Type of AI processing performed",
                        max_length=50,
                    ),
                ),
                (
                    "ai_model_used",
                    models.CharField(
                        help_text="AI model used for processing (e.g., gemini-2.5-pro)",
                        max_length=100,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence score of AI analysis (0.0 to 1.0)",
                        null=True,
                    ),
                ),
                (
                    "input_text",
                    models.TextField(help_text="Original text input to AI processing"),
                ),
                (
                    "structured_output",
                    models.JSONField(
                        blank=True,
                        help_text="Structured JSON output from AI processing",
                        null=True,
                    ),
                ),
                (
                    "generated_content",
                    models.TextField(
                        blank=True,
                        help_text="Generated content (emails, summaries, etc.)",
                        null=True,
                    ),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Time taken for AI processing in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of tokens used in AI processing",
                        null=True,
                    ),
                ),
                (
                    "cost_estimate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Estimated cost of AI processing in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if processing failed",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_processing_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_processing_results",
                        to="leases.lease",
                    ),
                ),
                (
                    "maintenance_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_processing_results",
                        to="maintenance.maintenancerequest",
                    ),
                ),
                (
                    "property_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_processing_results",
                        to="properties.property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_processing_results",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantApplicationAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applicant_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("current_address", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "employment_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("credit_score", models.IntegerField(blank=True, null=True)),
                ("rental_history", models.TextField(blank=True, null=True)),
                (
                    "risk_assessment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("recommendations", models.TextField(blank=True, null=True)),
                ("concerns", models.JSONField(blank=True, null=True)),
                ("pets_info", models.TextField(blank=True, null=True)),
                (
                    "move_in_timeline",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ai_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_application_analysis",
                        to="ai.aiprocessingresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority_assessment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "estimated_cost_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "estimated_cost_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("required_skills", models.JSONField(blank=True, null=True)),
                ("parts_needed", models.JSONField(blank=True, null=True)),
                ("safety_concerns", models.TextField(blank=True, null=True)),
                ("approach_recommendation", models.TextField(blank=True, null=True)),
                (
                    "timeline_estimate",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vendor_needed", models.BooleanField(default=False)),
                ("follow_up_required", models.BooleanField(default=False)),
                (
                    "ai_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_analysis",
                        to="ai.aiprocessingresult",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["priority_assessment"],
                        name="ai_maintena_priorit_1f8e68_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaseAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("property_address", models.TextField(blank=True, null=True)),
                (
                    "monthly_rent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("lease_start_date", models.DateField(blank=True, null=True)),
                ("lease_end_date", models.DateField(blank=True, null=True)),
                (
                    "security_deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "pet_deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("utilities_included", models.JSONField(blank=True, null=True)),
                ("special_terms", models.TextField(blank=True, null=True)),
                ("key_terms_summary", models.TextField(blank=True, null=True)),
                (
                    "extraction_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "ai_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lease_analysis",
                        to="ai.aiprocessingresult",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["lease_start_date", "lease_end_date"],
                        name="ai_leaseana_lease_s_8bf50d_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="aiprocessingresult",
            index=models.Index(
                fields=["processing_type", "status"],
                name="ai_aiproces_process_92e623_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiprocessingresult",
            index=models.Index(
                fields=["created_at"], name="ai_aiproces_created_93b606_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiprocessingresult",
            index=models.Index(
                fields=["property_obj", "processing_type"],
                name="ai_aiproces_propert_033186_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiprocessingresult",
            index=models.Index(
                fields=["tenant", "processing_type"],
                name="ai_aiproces_tenant__ace0e3_idx",
            ),
        ),
    ]
