# Generated by Django 4.2.27 on 2026-01-20 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_initial"),
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkCompletionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completion_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("satisfactory", "Satisfactory"),
                            ("poor", "Poor"),
                            ("incomplete", "Incomplete"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "issues_resolved",
                    models.JSONField(
                        blank=True,
                        help_text="List of issues that appear resolved",
                        null=True,
                    ),
                ),
                (
                    "remaining_issues",
                    models.JSONField(
                        blank=True,
                        help_text="Any remaining problems identified",
                        null=True,
                    ),
                ),
                (
                    "workmanship_quality",
                    models.TextField(
                        blank=True, help_text="Assessment of work quality", null=True
                    ),
                ),
                (
                    "compliance_check",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-compliant"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "follow_up_work",
                    models.TextField(
                        blank=True,
                        help_text="Any follow-up work recommended",
                        null=True,
                    ),
                ),
                (
                    "monitoring_needed",
                    models.BooleanField(
                        default=False, help_text="Whether ongoing monitoring is needed"
                    ),
                ),
                (
                    "before_photo_urls",
                    models.JSONField(
                        blank=True, help_text="URLs to before-work photos", null=True
                    ),
                ),
                (
                    "after_photo_urls",
                    models.JSONField(
                        blank=True, help_text="URLs to after-work photos", null=True
                    ),
                ),
                (
                    "ai_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_completion_analysis",
                        to="ai.aiprocessingresult",
                    ),
                ),
                (
                    "maintenance_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_completion_analyses",
                        to="maintenance.maintenancerequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Inspection"),
                            ("move_in", "Move-in Inspection"),
                            ("move_out", "Move-out Inspection"),
                            ("maintenance", "Maintenance Inspection"),
                            ("annual", "Annual Inspection"),
                            ("damage_assessment", "Damage Assessment"),
                        ],
                        help_text="Type of property inspection performed",
                        max_length=50,
                    ),
                ),
                (
                    "room_area",
                    models.CharField(
                        blank=True,
                        help_text="Specific room or area inspected",
                        max_length=100,
                    ),
                ),
                (
                    "overall_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "damage_description",
                    models.TextField(
                        blank=True,
                        help_text="Description of any damage or issues found",
                        null=True,
                    ),
                ),
                (
                    "maintenance_items",
                    models.JSONField(
                        blank=True,
                        help_text="List of maintenance items identified",
                        null=True,
                    ),
                ),
                (
                    "safety_concerns",
                    models.TextField(
                        blank=True,
                        help_text="Any safety issues or hazards detected",
                        null=True,
                    ),
                ),
                (
                    "estimated_repair_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated cost for repairs needed",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("emergency", "Emergency"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        blank=True,
                        help_text="Specific recommendations for property manager",
                        null=True,
                    ),
                ),
                (
                    "compliance_notes",
                    models.TextField(
                        blank=True,
                        help_text="Code compliance or regulatory concerns",
                        null=True,
                    ),
                ),
                (
                    "photo_urls",
                    models.JSONField(
                        blank=True,
                        help_text="URLs or references to inspection photos",
                        null=True,
                    ),
                ),
                (
                    "ai_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_inspection",
                        to="ai.aiprocessingresult",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["inspection_type", "overall_condition"],
                        name="ai_property_inspect_1a64aa_idx",
                    ),
                    models.Index(
                        fields=["urgency_level"], name="ai_property_urgency_eacb5e_idx"
                    ),
                ],
            },
        ),
    ]
