# Generated by Django 4.2.27 on 2026-01-20 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_workcompletionanalysis_propertyinspection"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_period",
                    models.CharField(
                        choices=[
                            ("3_months", "3 Months"),
                            ("6_months", "6 Months"),
                            ("12_months", "12 Months"),
                            ("24_months", "24 Months"),
                            ("custom", "Custom Period"),
                        ],
                        default="12_months",
                        help_text="Period covered by this financial analysis",
                        max_length=20,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly Report"),
                            ("quarterly", "Quarterly Report"),
                            ("annual", "Annual Report"),
                            ("investment", "Investment Analysis"),
                            ("forecast", "Financial Forecast"),
                        ],
                        default="monthly",
                        help_text="Type of financial report or analysis",
                        max_length=20,
                    ),
                ),
                (
                    "profitability_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "financial_ratios",
                    models.JSONField(
                        blank=True,
                        help_text="Key financial ratios and metrics",
                        null=True,
                    ),
                ),
                (
                    "trend_analysis",
                    models.JSONField(
                        blank=True,
                        help_text="Revenue, expense, and profit trends",
                        null=True,
                    ),
                ),
                (
                    "forecasts",
                    models.JSONField(
                        blank=True,
                        help_text="Financial projections and forecasts",
                        null=True,
                    ),
                ),
                (
                    "risk_assessment",
                    models.JSONField(
                        blank=True,
                        help_text="Financial risks and mitigation strategies",
                        null=True,
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        blank=True,
                        help_text="Specific recommendations for improvement",
                        null=True,
                    ),
                ),
                (
                    "benchmarking_insights",
                    models.TextField(
                        blank=True,
                        help_text="How property compares to market benchmarks",
                        null=True,
                    ),
                ),
                (
                    "investment_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent Investment"),
                            ("good", "Good Investment"),
                            ("fair", "Fair Investment"),
                            ("poor", "Poor Investment"),
                            ("high_risk", "High Risk - Avoid"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "expected_returns",
                    models.JSONField(
                        blank=True,
                        help_text="Projected returns and IRR calculations",
                        null=True,
                    ),
                ),
                (
                    "market_analysis",
                    models.JSONField(
                        blank=True,
                        help_text="Market conditions and competitive positioning",
                        null=True,
                    ),
                ),
                (
                    "generated_report",
                    models.TextField(
                        blank=True,
                        help_text="Full generated financial report content",
                        null=True,
                    ),
                ),
                (
                    "ai_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_analysis",
                        to="ai.aiprocessingresult",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["analysis_period", "report_type"],
                        name="ai_financia_analysi_3c94a3_idx",
                    ),
                    models.Index(
                        fields=["profitability_rating"],
                        name="ai_financia_profita_ac90b3_idx",
                    ),
                    models.Index(
                        fields=["investment_rating"],
                        name="ai_financia_investm_591b9c_idx",
                    ),
                ],
            },
        ),
    ]
