# Generated by Django 4.2.27 on 2026-01-20 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0003_property_version_alter_property_annual_property_tax_and_more",
        ),
        ("ai", "0003_financialanalysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("property_status", "Property Status Report"),
                            ("financial_summary", "Financial Summary"),
                            ("maintenance_overview", "Maintenance Overview"),
                            ("occupancy_update", "Occupancy Update"),
                            ("urgent_alerts", "Urgent Alerts"),
                        ],
                        help_text="Type of voice report generated",
                        max_length=50,
                    ),
                ),
                (
                    "report_text",
                    models.TextField(help_text="Full text content of the voice report"),
                ),
                (
                    "report_audio_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the generated audio report",
                        null=True,
                    ),
                ),
                (
                    "audio_duration_seconds",
                    models.FloatField(
                        blank=True, help_text="Duration of the audio report", null=True
                    ),
                ),
                (
                    "key_highlights",
                    models.JSONField(
                        blank=True,
                        help_text="Key highlights or summary points",
                        null=True,
                    ),
                ),
                (
                    "urgent_items",
                    models.JSONField(
                        blank=True,
                        help_text="Urgent items mentioned in the report",
                        null=True,
                    ),
                ),
                (
                    "recommended_actions",
                    models.JSONField(
                        blank=True,
                        help_text="Recommended actions from the report",
                        null=True,
                    ),
                ),
                (
                    "ai_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_report",
                        to="ai.aiprocessingresult",
                    ),
                ),
                (
                    "property_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_reports",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["report_type", "property_obj"],
                        name="ai_voicerep_report__af4f8d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VoiceInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("command", "Voice Command"),
                            ("report", "Voice Report"),
                            ("status_check", "Status Check"),
                            ("reminder", "Voice Reminder"),
                            ("help", "Help Request"),
                        ],
                        help_text="Type of voice interaction",
                        max_length=50,
                    ),
                ),
                (
                    "audio_transcript",
                    models.TextField(help_text="Transcribed text from voice input"),
                ),
                (
                    "audio_duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Duration of the audio input in seconds",
                        null=True,
                    ),
                ),
                (
                    "audio_file_url",
                    models.URLField(
                        blank=True, help_text="URL to stored audio file", null=True
                    ),
                ),
                (
                    "detected_intent",
                    models.CharField(
                        blank=True,
                        help_text="AI-detected intent from voice command",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "intent_confidence",
                    models.FloatField(
                        blank=True,
                        help_text="Confidence score for intent detection",
                        null=True,
                    ),
                ),
                (
                    "extracted_parameters",
                    models.JSONField(
                        blank=True,
                        help_text="Parameters extracted from voice command",
                        null=True,
                    ),
                ),
                (
                    "response_text",
                    models.TextField(
                        blank=True, help_text="Text response generated by AI", null=True
                    ),
                ),
                (
                    "response_audio_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to generated audio response",
                        null=True,
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        help_text="Action that was taken based on voice command",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "action_result",
                    models.JSONField(
                        blank=True, help_text="Result of the action taken", null=True
                    ),
                ),
                (
                    "needs_clarification",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the command needs clarification",
                    ),
                ),
                (
                    "clarification_question",
                    models.TextField(
                        blank=True,
                        help_text="Question to ask for clarification",
                        null=True,
                    ),
                ),
                (
                    "suggested_follow_ups",
                    models.JSONField(
                        blank=True,
                        help_text="Suggested follow-up actions or questions",
                        null=True,
                    ),
                ),
                (
                    "ai_result",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_interaction",
                        to="ai.aiprocessingresult",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["interaction_type", "detected_intent"],
                        name="ai_voiceint_interac_00fe02_idx",
                    ),
                    models.Index(
                        fields=["needs_clarification"],
                        name="ai_voiceint_needs_c_235088_idx",
                    ),
                ],
            },
        ),
    ]
