# Generated by Django 4.2.27 on 2026-01-20 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="document",
            name="documents_d_title_ccf306_idx",
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("doc", "Word Document"),
                    ("docx", "Word Document"),
                    ("xls", "Excel Spreadsheet"),
                    ("xlsx", "Excel Spreadsheet"),
                    ("txt", "Text File"),
                    ("jpg", "JPEG Image"),
                    ("png", "PNG Image"),
                    ("gif", "GIF Image"),
                    ("other", "Other"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["uploaded_by"], name="documents_d_uploade_6455fb_idx"
            ),
        ),
    ]
