# Generated by Django 6.0.1 on 2026-01-20 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0001_initial'),
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='property_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.property'),
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leases', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['status'], name='leases_leas_status_d62744_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['property_obj'], name='leases_leas_propert_849fba_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['lease_end_date'], name='leases_leas_lease_e_e3a1e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lease',
            unique_together={('property_obj', 'tenant', 'lease_start_date')},
        ),
    ]
