# Generated by Django 4.2.27 on 2026-01-20 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("email_payment_reminders", models.BooleanField(default=True)),
                ("email_maintenance_updates", models.BooleanField(default=True)),
                ("email_lease_updates", models.BooleanField(default=True)),
                ("email_system_updates", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("in_app_payment_reminders", models.BooleanField(default=True)),
                ("in_app_maintenance_updates", models.BooleanField(default=True)),
                ("in_app_lease_updates", models.BooleanField(default=True)),
                ("in_app_system_updates", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=False)),
                ("push_payment_reminders", models.BooleanField(default=False)),
                ("push_maintenance_updates", models.BooleanField(default=False)),
                ("push_lease_updates", models.BooleanField(default=False)),
                ("push_system_updates", models.BooleanField(default=False)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("never", "Never"),
                        ],
                        default="immediate",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "System Notification"),
                            ("payment", "Payment Notification"),
                            ("maintenance", "Maintenance Notification"),
                            ("lease", "Lease Notification"),
                            ("property", "Property Notification"),
                            ("tenant", "Tenant Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("related_model", models.CharField(blank=True, max_length=100)),
                ("related_id", models.PositiveIntegerField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("action_url", models.URLField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="users_notif_user_id_1be17e_idx",
                    ),
                    models.Index(
                        fields=["user", "notification_type"],
                        name="users_notif_user_id_c58e16_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="users_notif_created_3ee999_idx"
                    ),
                ],
            },
        ),
    ]
