# Generated by Django 4.2.27 on 2026-01-20 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_notificationpreference_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_phone_number",
                        message="Enter a valid phone number.",
                        regex="^\\+?1?[-.\\s]?\\(?([0-9]{3})\\)?[-.\\s]?([0-9]{3})[-.\\s]?([0-9]{4})$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="zip_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_zip_code",
                        message="Enter a valid ZIP code.",
                        regex="^\\d{5}(-\\d{4})?$",
                    )
                ],
            ),
        ),
    ]
